apiVersion: v1
kind: Service
metadata:
  name: incwebdemo
spec:
  selector:
    app: incwebdemo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
  type: NodePort
