// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/crosscode-nl/incwebdemo/application"
	"github.com/crosscode-nl/incwebdemo/memoryincrementer"
	"github.com/crosscode-nl/incwebdemo/redisincrementer"
)

// Injectors from wire.go:

func InitializeMemoryApp() *application.App {
	memIncrementer := memoryincrementer.New()
	app := application.New(memIncrementer)
	return app
}

func InitializeRedisApp() *application.App {
	config := redisincrementer.NewConfig()
	redisIncrementer := redisincrementer.NewRedisIncrementer(config)
	app := application.New(redisIncrementer)
	return app
}
